### ISSUE TITLE
Move from TLSv1 to TLSv1_2

### ISSUE THREAD

**Issue by troyhebe** [HewlettPackard/python-hpICsp#1]
Here is a patch to enable TSLv1_2 support, I just added the same patch to the python-hpOneView. Please note that this patch also forces the move to Python 3.4 as the minimum supported version.

diff --git a/hpICsp/**init**.py b/hpICsp/**init**.py
index b015cda..b388d1a 100644
--- a/hpICsp/**init**.py
+++ b/hpICsp/**init**.py
@@ -35,8 +35,8 @@ **status** = 'Development'
 ###

 import sys
-if sys.version_info < (3, 2):
-    raise Exception('Must use Python 3.2 or later')
  +if sys.version_info < (3, 4):
-    raise Exception('Must use Python 3.4 or later')
  
  from hpICsp.common import *
  from hpICsp.exceptions import *

diff --git a/hpICsp/connectionHPOneView.py b/hpICsp/connectionHPOneView.py
index 8013fd2..76ba05a 100644
--- a/hpICsp/connectionHPOneView.py
+++ b/hpICsp/connectionHPOneView.py
@@ -105,7 +105,7 @@ class connectionHPOneView(object):
             try:
                 if self._sslTrustAll is False:
                     import ssl
-                    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
-                    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
                   context.verify_mode = ssl.CERT_REQUIRED
                   context.load_verify_locations(self._sslTrustedBundle)
                   if self._doProxy is False:
  @@ -118,11 +118,16 @@ class connectionHPOneView(object):
                       conn.set_tunnel(self._host, 443)
                   conn.request(method, path, body, self._headers)
               else:
-                    import ssl
-                    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
-                    context.verify_mode = ssl.CERT_NONE
                   if self._doProxy is False:
-                        conn = http.client.HTTPSConnection(self._host)
-                        conn = http.client.HTTPSConnection(self._host,
-                                                           context=context)
                   else:
                       conn = http.client.HTTPSConnection(self._proxyHost,
-                                                           self._proxyPort)
-                                                           self._proxyPort,
-                                                           context=context)
                       conn.set_tunnel(self._host, 443)
                   conn.request(method, path, body, self._headers)
               resp = conn.getresponse()

**Comment by cboeker** [comment]
fixed with commit https://github.com/HewlettPackard/python-hpICsp/commit/91f41f4bf48717d7c92c299626561c01dbbf729c
